#!/usr/bin/env python3
import qpycmd
from qpycmd import QPyCMD
import os

os.environ["QEXTPATH"] = os.path.abspath(os.path.dirname(qpycmd.__file__)) + "/.ext/"
os.environ["QUPDATEPATH"] =  qpycmd.__file__

if __name__ == "__main__":
	q = QPyCMD()
	q.mainloop()
